# Generated by Django 2.2.19 on 2021-03-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penilai',
            old_name='dinilai',
            new_name='pegawai',
        ),
    ]
