# Generated by Django 2.2.19 on 2021-02-28 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indikator',
            options={'verbose_name_plural': ' Indikator Kegiatan'},
        ),
        migrations.AlterModelOptions(
            name='jabatan',
            options={'verbose_name_plural': '      Jabatan'},
        ),
        migrations.AlterModelOptions(
            name='pegawai',
            options={'verbose_name_plural': '     Pegawai'},
        ),
        migrations.AlterModelOptions(
            name='pejabatpenilai',
            options={'verbose_name_plural': '    Pejabat Penilai'},
        ),
        migrations.AlterModelOptions(
            name='sasaran',
            options={'verbose_name_plural': '   Sasaran Kegiatan'},
        ),
        migrations.AlterModelOptions(
            name='satuan',
            options={'verbose_name_plural': '  Satuan'},
        ),
        migrations.AlterField(
            model_name='jabatan',
            name='nama',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='jabatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kinerja.Jabatan'),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='nip',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sasaran',
            name='nama',
            field=models.TextField(max_length=500, null=True, verbose_name='Sasaran Kegiatan'),
        ),
    ]
