# Generated by Django 2.2.19 on 2021-02-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0003_auto_20210228_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='golrung',
            field=models.CharField(max_length=5, null=True, verbose_name='Golongan(Ruang)'),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='nip',
            field=models.CharField(max_length=21, null=True, verbose_name='NIP'),
        ),
    ]
