# Generated by Django 2.2.19 on 2021-02-28 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0006_auto_20210228_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pejabatpenilai',
            name='atasan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atasan', to='kinerja.Pegawai', verbose_name='Pejabat Penilai'),
        ),
        migrations.AlterField(
            model_name='pejabatpenilai',
            name='pegawai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai', to='kinerja.Pegawai', verbose_name='Pegawai Yang Dinilai'),
        ),
    ]
