# Generated by Django 2.2.19 on 2021-02-28 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0008_auto_20210228_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indikator',
            old_name='kualitas',
            new_name='target_kuantitas',
        ),
        migrations.RemoveField(
            model_name='indikator',
            name='angka_kredit',
        ),
        migrations.RemoveField(
            model_name='indikator',
            name='kuantitas',
        ),
        migrations.AddField(
            model_name='indikator',
            name='pagu_anggaran',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='indikator',
            name='target_mutu',
            field=models.IntegerField(default=1, null=True, verbose_name='Target Mutu'),
        ),
        migrations.AddField(
            model_name='indikator',
            name='waktu_penyelesaian',
            field=models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='indikator',
            name='satuan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kinerja.Satuan'),
        ),
    ]
