# Generated by Django 2.2.19 on 2021-02-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0009_auto_20210228_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulanPenyelesaian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': '  Bulan',
            },
        ),
        migrations.AlterModelOptions(
            name='jabatan',
            options={'verbose_name_plural': '       Jabatan'},
        ),
        migrations.AlterModelOptions(
            name='pegawai',
            options={'verbose_name_plural': '      Pegawai'},
        ),
        migrations.AlterModelOptions(
            name='pejabatpenilai',
            options={'verbose_name_plural': '     Pejabat Penilai'},
        ),
        migrations.AlterModelOptions(
            name='sasaran',
            options={'verbose_name_plural': '    Sasaran Kegiatan'},
        ),
        migrations.AlterModelOptions(
            name='satuan',
            options={'verbose_name_plural': '   Satuan'},
        ),
        migrations.RemoveField(
            model_name='indikator',
            name='waktu_penyelesaian',
        ),
        migrations.AddField(
            model_name='indikator',
            name='waktu_penyelesaian',
            field=models.ManyToManyField(to='kinerja.BulanPenyelesaian'),
        ),
    ]
